name: .NET
env:
  acr-name: 'openhackkv74imm5acr.azurecr.io'
  repository-name: 'devopsoh/api-poi'
  res-group: 'openhackkv74imm5rg'
  appsvc-name: 'openhackkv74imm5poi'
  working-directory: ./apis/poi/
on:
  push:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./apis/poi/
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore	  
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload build    
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{ env.working-directory }}web/
    - name: Logging to Azure Boards on failure
      uses: stefanstranger/azuredevops-bug-action@1.1  
      if: failure()
      with:
        OrganizationName: "SuperSix"
        PAT: "PAT"
        ProjectName: "SuperSixInsurance"
        AreaPath: "SuperSixInsurance\\DeploymentArea"
        IterationPath: "SuperSixInsurance"
        GithubToken: "GithubToken"
        WorkflowFileName: "dotnet.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}
      
  Push-to-Container-Registry:
    runs-on: ubuntu-latest
    needs: [build]

    
    steps:

      
    - name: Download build    
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Debug Check path
      run: |
        pwd
        ls -la
      shell: bash        
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Build_PushDocker
      run: az acr build --image "${{ env.repository-name }}:${{ github.run_number }}" --registry ${{ env.acr-name }} --file Dockerfile .
    
      
    - name: Image digest
      run: echo ${{ steps.Build_PushDocker.outputs.digest }} 
     
    - name: Logging to Azure Boards on failure
      uses: stefanstranger/azuredevops-bug-action@1.1  
      if: failure()
      with:
          OrganizationName: "SuperSix"
          PAT: "PAT"
          ProjectName: "SuperSixInsurance"
          AreaPath: "SuperSixInsurance\\DeploymentArea"
          IterationPath: "SuperSixInsurance"
          GithubToken: "GithubToken"
          WorkflowFileName: "dotnet.yml"
      env:
            PAT: ${{ secrets.PAT}}
            GithubToken: ${{ secrets.githubtoken}}
            
  deploy-to-Stage:
    runs-on: ubuntu-latest
    needs: [Push-to-Container-Registry]
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: 'Deploy to Azure App service' 
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackkv74imm5poi'
        images: "${{ env.repository-name }}:${{ github.run_number }}"
        slot-name: 'staging'
    - name: Restart App service
      run: az webapp start -g ${{ env.res-group }} -n ${{ env.appsvc-name }} --slot staging 
    - name: Logging to Azure Boards on failure
      uses: stefanstranger/azuredevops-bug-action@1.1  
      if: failure()
      with:
          OrganizationName: "SuperSix"
          PAT: "PAT"
          ProjectName: "SuperSixInsurance"
          AreaPath: "SuperSixInsurance\\DeploymentArea"
          IterationPath: "SuperSixInsurance"
          GithubToken: "GithubToken"
          WorkflowFileName: "dotnet.yml"
      env:
            PAT: ${{ secrets.PAT}}
            GithubToken: ${{ secrets.githubtoken}}
